name: Cache Revalidation

on:
  push:
    branches:
      - master

jobs:
  revalidate_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3

      - name: Update Image URL with Query Parameter
        run: |
          python3 -c '
          import re

          with open("README.md", "r") as file:
              content = file.read()

          pattern = r"(?<=!\[.*\]\()(http[^)]+)(?=\))"
          updated_content = re.sub(pattern, lambda match: match.group() + "&r=$(date +%s)", content)

          with open("README.md", "w") as file:
              file.write(updated_content)
          '

      - name: Revalidate Cache
        run: |
          IMAGE_URL=$(grep -Eo '\[!\[.*\]\((http[^)]+)\)' README.md | perl -pe 's/.*\((http[^)]+)\).*/\1/')
          IMAGE_PATH=$(echo "${IMAGE_URL}" | perl -pe 's/^.*\/(\w+)(\?.*)?$/\1/')
          curl -X PURGE "https://api.roadmap.sh/v1-badge/long/${IMAGE_PATH}"

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "arikchangma@gmail.com"
          git add README.md
          git commit -m "Update image URL with random query parameter [skip ci]"
          git push origin master
