name: Cache Revalidation

on:
  push:
    branches:
      - master

jobs:
  revalidate_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Makefile
        run: make revalidate_cache
